#!/usr/bin/env python3
"""Regenerate Q3 floor projection without floating point on the target."""
from pathlib import Path
SINE = [0,25,49,71,90,106,117,125,127,125,117,106,90,71,49,25,0,-25,-49,-71,-90,-106,-117,-125,-127,-125,-117,-106,-90,-71,-49,-25]
DISTANCE = [593,480,403,348,305,272,246,224,206,190,177,165,155,146,138,131,124,119,113,108,104,100,96,92]
STRIDE = [45,37,31,27,23,21,19,17,16,14,13,13,12,11,11,10,9,9,9,8,8,8,7,7]
def trunc(a,b):
    return (abs(a)//b)*(-1 if a<0 else 1)
def generate():
    lines=['/* Q3 projection parameters, generated by tools/pce/floor_tables.py. */', 'static const int16_t geometry[32][24][4] __attribute__((section(".ram_bank109.rodata"))) = {']
    for h in range(32):
        sn=SINE[h];cs=SINE[(h+8)&31];rows=[]
        for distance,stride in zip(DISTANCE,STRIDE):
            du=trunc(-sn*stride,128);dv=trunc(cs*stride,128)
            rows.append('{%d,%d,%d,%d}'%(trunc(cs*distance,16)-du*64,trunc(sn*distance,16)-dv*64,du,dv))
        lines.append('{'+','.join(rows)+'},')
    return '\n'.join(lines+['};'])+'\n'
if __name__=='__main__':
    (Path(__file__).resolve().parents[2]/'src/platform/pce/floor_geometry.h').write_text(generate())
